package modelo.model;
// Generated 17/06/2017 10:36:28 AM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idpersona;
     private String nombre;
     private String paterno;
     private String materno;
     private String curp;
     private String correo;
     private Integer edad;
     private String password;

    public Persona() {
    }

	
    public Persona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(int idpersona, String nombre, String paterno, String materno, String curp, String correo, Integer edad, String password) {
       this.idpersona = idpersona;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.curp = curp;
       this.correo = correo;
       this.edad = edad;
       this.password = password;
    }
    
    public Persona( String nombre, String paterno, String materno, String curp, String correo, Integer edad, String password) {
       
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.curp = curp;
       this.correo = correo;
       this.edad = edad;
       this.password = password;
    }

    
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


